Make lwt-create relative to working directory

diff --git a/lwt-create b/lwt-create
--- a/lwt-create
+++ b/lwt-create
@@ -1,66 +1,121 @@
 #!/bin/bash
 # Create - Lars Web Tools
 
-if [ -d $WEB_DIR -o -f $VIRTUAL_HOST_FILE ]; then
-	echo "The directory [$WEB_DIR] or the virtual host file [$VIRTUAL_HOST_FILE] already exists."
-	echo "Aborting."
+
+readonly GREP_SUCCESS=0
+readonly TLD=".localhost"
+
+function abort {
+	echo $(date +%FT%T) ${BASH_SOURCE[1]##*/}[${BASH_LINENO[0]}]: "${@}"
+	echo "Aborting"
+	exit 1
+}
+
+function apache::version {
+	if [ "$#" -ne 1 ]; then abort "Not enough parameters."; fi
+
+	local __return=$1
+
+	apachectl -v &> /dev/null
+	if [ $? -ne 0 ]; then
+		abort "Error running \`apachectl -v\`."
+	fi
+
+	local apache_ver="`apachectl -v 2> /dev/null`"
+	apache_ver=`echo "$apache_ver" | grep "Server version"`
+	apache_ver=`expr "$apache_ver" : 'Server version: Apache/\(.*\) .*'`
+	eval $__return="'$apache_ver'"
+}
+
+function apache::config_get {
+	if [ "$#" -ne 2 ]; then abort "Not enough parameters."; fi
+
+	local __return=$1
+	local __key=$2
+
+	apachectl -S &> /dev/null
+	if [ $? -ne 0 ]; then
+		abort "Error running \`apachectl -S\`."
+	fi
+
+	local conf="`apachectl -S 2> /dev/null`"
+	conf=`echo "$conf" | grep "${__key}"`
+	conf=`expr "$conf" : "${__key}: \"\(.*\)\""`
+	eval $__return="'$conf'"
+}
+
+if [ "$#" -ne 1 ]; then
+	echo "Usage: $0 PROJECT"
 	exit 1
 fi
 
-grep -q "$LOCAL_DOMAIN" "$ETC_HOSTS_FILE"
+SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+apache::config_get APACHE_DIR "ServerRoot"
+PROJECT=$1
+PROJECT_DIR="`pwd`/${PROJECT}"
+DOMAIN="${PROJECT}${TLD}"
+VHOST="${APACHE_DIR}/sites-available/${DOMAIN}.conf"
+VHOST_CONFIG=$(source ${SCRIPT_PATH}/lwt_vhost_conf)
+
+if [ ! -d "${APACHE_DIR}/sites-available" ]; then
+	abort "Could not find apache's site configuration directory."
+fi
+
+if [ -d "$PROJECT" ]; then
+	abort "The directory [$PROJECT] already exists."
+fi
+
+if [ -f "$VHOST" -o -h "$VHOST" ]; then
+	abort "The virtual host file [$VHOST] already exists."
+fi
+
+grep -q "$DOMAIN" /etc/hosts
 if [ $? -eq $GREP_SUCCESS ]; then
-	echo "The domain [$LOCAL_DOMAIN] is already present in [$ETC_HOSTS_FILE]. This script will not add it again."
+	echo "The domain [$DOMAIN] is already present in [/etc/hosts]. This script will not add it again."
 	echo "Do you wish to continue? (y/n)"
 	read REPLY
 	if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+		abort
 		exit 1
 	fi
 fi
 
 # Get sudo permissions
+echo "We need root permissions to add the virtual host."
 sudo echo -n ""
 if [ $? -eq 1 ]; then
-	echo "Permission denied"
-	exit 1
+	abort "Permission denied"
 fi
 
 # Create folders and copy default files
-echo -n "Creating web directory with default folder structure in [$WEB_DIR]... "
-mkdir "$WEB_DIR"
+echo -n "Creating web directory with default folder structure in [$PROJECT_DIR]... "
+mkdir "$PROJECT_DIR"
 
-mkdir "$WEB_DIR_PUBLIC"
-mkdir "$WEB_DIR/data"
-mkdir "$WEB_DIR/data/logs"
+mkdir "${PROJECT_DIR}/public"
+mkdir "${PROJECT_DIR}/data"
+mkdir "${PROJECT_DIR}/data/logs"
 echo "done!"
 
-if [ -n "$2" ]; then
-	if [ -d "$SCRIPT_PATH/default_project/$2" -a -f "$SCRIPT_PATH/default_project/$2/$2_create" ]; then
-		source "$SCRIPT_PATH/default_project/$2/$2_create"
-	else
-		echo "Unknown project type [$2]."
-	fi
-fi
-
 # Create Virtual Host
-echo -n "Creating Virtual Host for [$LOCAL_DOMAIN]... "
-mkdir "$WEB_DIR/data/vhost"
-echo "$VIRTUAL_HOST_STRING" > "$WEB_DIR/data/vhost/vhost.apache2"
-sudo ln -s "$WEB_DIR/data/vhost/vhost.apache2" "$VIRTUAL_HOST_FILE"
+echo -n "Creating Virtual Host for [$DOMAIN]... "
+mkdir "${PROJECT_DIR}/data/vhost"
+echo "$VHOST_CONFIG" > "${PROJECT_DIR}/data/vhost/vhost.apache2"
+sudo ln -s "${PROJECT_DIR}/data/vhost/vhost.apache2" "$VHOST"
 echo "done!"
 
 # Enable Virtual Host
-echo -n "Enabling Virtual Host for [$LOCAL_DOMAIN]... "
-sudo sh -c "a2ensite \"$LOCAL_DOMAIN\" > /dev/null"
+echo -n "Enabling Virtual Host for [$DOMAIN]... "
+sudo sh -c "a2ensite \"$DOMAIN\" > /dev/null"
 echo "done!"
 
 # Add entry in /etc/hosts
-echo -n "Adding entry in [$ETC_HOSTS_FILE]... "
-grep -q "$LOCAL_DOMAIN" "$ETC_HOSTS_FILE"
+echo -n "Adding entry in /etc/hosts... "
+grep -q "$DOMAIN" "/etc/hosts"
 if [ ! $? -eq $GREP_SUCCESS ]; then
-	sudo sh -c "echo \"$LOCAL_IP\t$LOCAL_DOMAIN\" >> \"$ETC_HOSTS_FILE\""
+	sudo sh -c "echo \"127.0.0.1\t$DOMAIN\" >> \"/etc/hosts\""
 	echo "done!"
 else
-	echo "NOT done! Host is already present in [$ETC_HOSTS_FILE]."
+	echo "NOT done! Host is already present in [/etc/hosts]."
 fi
 
 echo
