Sudo remove projects

diff --git a/lwt-delete b/lwt-delete
--- a/lwt-delete
+++ b/lwt-delete
@@ -2,15 +2,15 @@
 # Delete - Lars Web Tools
 
 # This check is not really necessary.
-#if [ ! -d $WEB_DIR -o ! -f $VIRTUAL_HOST_FILE ]; then
-#	echo "The directory [$WEB_DIR] or the virtual host file [$VIRTUAL_HOST_FILE] doesn't exist."
-#	echo "Aborting."
-#	exit 1
-#fi
+if [ ! -d $WEB_DIR -o ! -f $VIRTUAL_HOST_FILE ]; then
+	echo "The directory [$WEB_DIR] or the virtual host file [$VIRTUAL_HOST_FILE] doesn't exist."
+	echo "Aborting."
+	exit 1
+fi
 
 echo "Do you wish to DELETE [$LOCAL_DOMAIN] and ALL CONTENT in [$WEB_DIR]? This action can not be undone."
 echo "Continue? (y/n)"
-read REPLY 
+read REPLY
 if [[ ! $REPLY =~ ^[Yy]$ ]]
 then
 	exit 1
@@ -24,7 +24,7 @@ if [ $? -eq 1 ]; then
 fi
 
 echo -n "Deleting folder [$WEB_DIR] and all content... "
-rm -r "$WEB_DIR"
+sudo rm -r "$WEB_DIR"
 echo "done!"
 
 echo -n "Disabling the Virtual Host for [$LOCAL_DOMAIN]... "
@@ -47,6 +47,6 @@ else
 	echo "aborted. Host is not present in [$ETC_HOSTS_FILE]."
 fi
 
-echo 
+echo
 echo "Reload apache for changes to take effect."
-echo 
+echo
